server:
  port: 11244
  max-http-header-size: 10240

spring:
  datasource:
    ## uat环境
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@//6.106.4.52:1521/qinnong
#    url: jdbc:oracle:thin:@//6.106.16.104:1521/orcl
    url: jdbc:oracle:thin:@//6.106.16.104:1521/QNA
    #QN_DB_ACCT  123456
#    username: SYSTEM
#    password: qinnong
    username: QN_DB_ACCT
    password: 123456
    filters: wall,mergeStat
    druid:
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
  data-source-name: acctPrintdb

storage:
  tempUpload:
    path: /data/acctprint/fileserver/upload/
#    path: D:\data\acctprint\fileserver\upload\
  tempDownload:
    path: /data/acctprint/fileserver/download/
  remote:
    path: /file/
  configPath: /ftpClientConfig.properties
  qnUploadtranCode: 100030
  accDowntranCode: 100024

xxl:
  job:
    admin:
      addresses: http://6.106.4.23:8080/xxl-job-admin/
    executor:
      appname: acctPrint
      ip:
      port: 8099
      #accessToken:
      logpath: /data/logs/acctprint/xxl-job/
      logretentiondays: -1


#afe:
#  lspublic:
#    Key:
#      path: /data/accprint/cer/113700.cer
#  private:
#    Key:
#      path: /data/accprint/cer/113501.pfx