spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  aop:
    proxy-target-class: true

mybatis-plus:
  type-aliases-package: com.tkcx.api.business.*.model
  mapper-locations: classpath*:com/tkcx/api/business/*/dao/mapping/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
      # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true
    #关闭mybatis日志输出
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    #开启mybatis日志输出
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

