server:
  port: 11245
  max-http-header-size: 10240

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//oracle.bank.com:1521/qnxywd
    username: QN_DB_ACCT
    password: qnwd123
    filters: wall,mergeStat
    druid:
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
  data-source-name: acctPrintdb

storage:
  tempUpload:
    path: /home/loan/fileserver/upload/
  tempDownload:
    path: /home/loan/fileserver/download/
  remote:
    path: /file/
  configPath: /ftpClientConfig.properties
  qnUploadtranCode: 100030
  accDowntranCode: 100024

xxl:
  job:
    admin:
      addresses: http://xxl.bank.com/xxl-job-admin/
    executor:
      appname: acctprint
      ip:
      port: 8099
      #accessToken:
      logpath: /home/loan/logs/newloan/xxl-job/
      logretentiondays: -1


afe:
  lspublic:
    Key:
      #AFE公钥路径
      path: /data/acctprint/afe_acct/113700.cer
  private:
    Key:
      #本系统私钥路径
      path: /data/acctprint/afe_acct/113501.pfx
  passwd: 123456
  socket:
    #报文请求服务器
    ip: 5.101.96.60
  upload:
    #上传报文请求端口
    port: 21703
  #??20220902?????
  download:
    #同步下载报文请求端口
    port: 21705
  sec:
    node:
      #系统节点号
      id: 113501
  #AFE-SFTP
  sftp:
    #SFTP服务器IP
    host: 5.101.96.60
    #SFTP服务器端口
    port: 20022
    #SFTP用户名
    username: 113501
    #SFTP
    password: 113501
    #SFTP服务器基础路径
    basePath: /113501/
    #SFTP 文服上传方式 1-集中式 2-分布式，不送默认走集中式
    FileServerType: 1
    #SFTP 分布式文服节点
    DisNode: ""
#新希望推送文件路径
newLoan:
  filePath: D:\\JAVA\\Company\\new_loan\\file_data\\
#  filePath: /home/loan/file_data/