server:
  port: 11244
  max-http-header-size: 10240

spring:
  datasource:
    ## sit环境
    driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@//6.106.4.52:1521/qinnong
      username: QN_DB_ACCT
      password: 123456
    filters: wall,mergeStat
    druid:
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
  data-source-name: acctPrintdb

storage:
  tempUpload:
    path: /data/acctprint/fileserver/upload/
  tempDownload:
    path: /data/acctprint/fileserver/download/
  remote:
    path: /file/
  configPath: /ftpClientConfig.properties
  qnUploadtranCode: 100030
  accDowntranCode: 100024


xxl:
  job:
    admin:
      addresses: http://6.106.4.23:8080/xxl-job-admin/
    executor:
      appname: acctPrint
      ip: 6.106.4.15
      ## SIT 6.106.4.15
      ## UAT 6.106.4.25
      port: 8098
      ## SIT 8098
      ## UAT 8099
      #accessToken:
      logpath: /data/logs/acctprint/xxl-job/
      logretentiondays: -1



afe:
  lspublic:
    Key:
      #AFE公钥路径
      path: D:\JAVA\Company\bersion_gitlab\kjpz\src\main\resources\rsa_2048\113700.cer
  private:
    Key:
      #本系统私钥路径
      path: D:\JAVA\Company\bersion_gitlab\kjpz\src\main\resources\rsa_2048\113501.pfx
  passwd: 123456
  socket:
    #报文请求服务器
    ip: 6.106.4.50
  upload:
    #上传报文请求端口
    port: 21707
  download:
    #同步下载报文请求端口
    port: 21705
  sec:
    node:
      #系统节点号
      id: 113501
    #AFE-SFTP
  sftp:
    #SFTP服务器IP
    host: 6.106.4.50
    #SFTP服务器端口
    port: 22
    #SFTP用户名
    username: 113501
    #SFTP
    password: 113501
    #SFTP服务器基础路径
    basePath: /nfs/113501/
    #SFTP 文服上传方式 1-集中式 2-分布式，不送默认走集中式
    FileServerType: 1
    #SFTP 分布式文服节点
    DisNode: ""
